theme: jekyll-theme-minimal
logo: "./logo.jpg"
title: Evan Cesanek
description: Evan Cesanek is a cognitive scientist with expertise in experimental design, data science, and software engineering. He earned his PhD from Brown University and works as a Research Scientist in Columbia University's Zuckerman Institute. His work focuses on human sensorimotor function.
